In [1]:
# Dependencies
import pandas as pd
import numpy as np

In [2]:
# Name of the CSV file

Articles_Apr = "Resources/ArticlesApril2018.csv"
Articles_Feb ="Resources/ArticlesFeb2018.csv"
Articles_Jan = "Resources/ArticlesJan2018.csv"
Articles_Mar = "Resources/ArticlesMarch2018.csv"

In [3]:
# Rread the CSV in pandas

df_Articles_Apr = pd.read_csv(Articles_Apr)
df_Articles_Feb = pd.read_csv(Articles_Feb)
df_Articles_Jan = pd.read_csv(Articles_Jan)
df_Articles_Mar = pd.read_csv(Articles_Mar)

In [4]:
# Preview of the DataFrame
df_Articles_Apr

,articleID,articleWordCount,byline,documentType,headline,keywords,multimedia,newDesk,printPage,pubDate,sectionName,snippet,source,typeOfMaterial,webURL
0,5adf6684068401528a2aa69b,781,By JOHN BRANCH,article,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",68,Sports,0,4/24/2018 17:16,Pro Football,"“I understand that they could meet with us, pa...",The New York Times,News,https://www.nytimes.com/2018/04/24/sports/foot...
1,5adf653f068401528a2aa697,656,By LISA FRIEDMAN,article,E.P.A. to Unveil a New Rule. Its Effect: Less ...,"['Environmental Protection Agency', 'Pruitt, S...",68,Climate,0,4/24/2018 17:11,Unknown,The agency plans to publish a new regulation T...,The New York Times,News,https://www.nytimes.com/2018/04/24/climate/epa...
2,5adf4626068401528a2aa628,2427,By PETE WELLS,article,"The New Noma, Explained","['Restaurants', 'Noma (Copenhagen, Restaurant)...",66,Dining,0,4/24/2018 14:58,Unknown,What’s it like to eat at the second incarnatio...,The New York Times,News,https://www.nytimes.com/2018/04/24/dining/noma...
3,5adf40d2068401528a2aa619,626,By JULIE HIRSCHFELD DAVIS and PETER BAKER,article,Unknown,"['Macron, Emmanuel (1977- )', 'Trump, Donald J...",68,Washington,0,4/24/2018 14:35,Europe,President Trump welcomed President Emmanuel Ma...,The New York Times,News,https://www.nytimes.com/2018/04/24/world/europ...
4,5adf3d64068401528a2aa60f,815,By IAN AUSTEN and DAN BILEFSKY,article,Unknown,"['Toronto, Ontario, Attack (April, 2018)', 'Mu...",68,Foreign,0,4/24/2018 14:21,Canada,"Alek Minassian, 25, a resident of Toronto’s Ri...",The New York Times,News,https://www.nytimes.com/2018/04/24/world/canad...
5,5adf341f068401528a2aa5e8,1233,By NICHOLAS FANDOS and MICHAEL D. SHEAR,article,Unknown,"['United States Politics and Government', 'Vet...",68,Washington,0,4/24/2018 13:41,Politics,The Senate Veterans Affairs Committee is exami...,The New York Times,News,https://www.nytimes.com/2018/04/24/us/politics...
6,5adf2a0f068401528a2aa5c8,871,By ADAM NAGOURNEY and CHARLES McDERMID,article,Unknown,[],0,NYTNow,0,4/24/2018 12:58,Unknown,Tuesday: Rent control appears headed to the ba...,The New York Times,briefing,https://www.nytimes.com/2018/04/24/us/californ...
7,5adf26cf068401528a2aa5c1,938,By NIRAJ CHOKSHI,article,Unknown,"['Presidential Election of 2016', 'Proceedings...",68,Express,0,4/24/2018 12:45,Politics,"A new study suggests that the white, Christian...",The New York Times,News,https://www.nytimes.com/2018/04/24/us/politics...
8,5adf2108068401528a2aa5b3,730,By JOHN SCHWARTZ,article,How a Bag of Texas Dirt Became a Times Tradition,"['Texas', 'Soil', 'Pregnancy and Childbirth', ...",68,Insider,2,4/24/2018 12:20,Unknown,What can you do when you want your child to be...,The New York Times,News,https://www.nytimes.com/2018/04/24/insider/how...
9,5adedaa8068401528a2aa4e6,482,By NATALIE PROULX,article,Is School a Place for Self-Expression?,[],66,Learning,0,4/24/2018 11:21,Unknown,Are you encouraged to question and articulate ...,The New York Times,News,https://www.nytimes.com/2018/04/24/learning/is...
10,5adf0063068401528a2aa552,475,By GRETCHEN REYNOLDS,article,Commuter Reprogramming,"['Bicycles and Bicycling', 'Google Maps', 'Com...",66,Magazine,20,4/24/2018 10:01,Unknown,People often overestimate the time required to...,The New York Times,News,https://www.nytimes.com/2018/04/24/well/think-...
11,5adf0024068401528a2aa551,1335,By ALEXANDRA S. LEVINE,article,Unknown,['New York City'],68,Metro,0,4/24/2018 10:00,Unknown,"Tuesday: Revisiting the New York World’s Fair,...",The New York Times,briefing,https://www.nytimes.com/2018/04/24/nyregion/ne...
12,5adef286068401528a2aa537,776,By TIM McKEOUGH,article,Unknown,"['Interior Design and Furnishings', 'Real Esta...",68,RealEstate,0,4/24/2018 9:01,Unknown,"For a pair of designers in Brooklyn, getting a...",The New York Times,News,https://www.nytimes.com/2018/04/24/realestate/...
13,5adef237068401528a2aa532,1185,By NEAL E. BOUDETTE,article,"Ford Changed Leaders, Looking for a Lift. It’s...","['Hackett, Jim', 'Ford Motor Co', 'Automobiles...",66,Business,0,4/24/2018 9:00,Unknown,"After 11 months as chief, Jim Hackett has yet ...",The New York Times,News,https://www.nytimes.com/2018/04/24/business/fo...
14,5adef237068401528a2aa531,1091,By JULIE TURKEWITZ and JONATHAN MARTIN,article,"Romney Failed to Win at Utah Convention, But F...","['Romney, Mitt', 'Elections, Senate', 'Utah', ...",67,Politics,0,4/24/2018 9:00,Politics,"The 2012 G.O.P. presidential nominee, running ...",The New York Times,News,https://www.nytimes.com/2018/04/24/us/politics...
15,5adef230068401528a2aa527,1450,By CAMERON TUNG,article,Chain Reaction,"['Social Media', 'Conservatism (US Politics)',...",66,Magazine,9,4/24/2018 9:00,Unknown,Every bit of news sparks tidy cycles of backla...,The New York Times,News,https://www.nytimes.com/2018/04/24/magazine/on...
16,5adef233068401528a2aa52c,1069,By LAURIE GOODSTEIN,article,He Forced the Vatican to Investigate Sex Abuse...,"['Francis', 'Roman Catholic Church', 'Karadima...",68,National,0,4/24/2018 9:00,Unknown,Juan Carlos Cruz was sexually abused by one of...,The New York Times,News,https://www.nytimes.com/2018/04/24/us/sex-abus...
17,5adef22f068401528a2aa525,1096,By TED LOOS,article,"In Berlin, artists find a home","['Art', 'Berlin (Germany)', 'Ai Weiwei', 'Bies...",68,SpecialSections,1,4/24/2018 9:00,Unknown,"It’s a city friendly to the creative crowd, wi...",International New York Times,News,https://www.nytimes.com/2018/04/24/arts/berlin...
18,5adef226068401528a2aa520,1583,By JESS BIDGOOD and SABRINA TAVERNISE,article,Unknown,"['Gun Control', 'Parkland, Fla, Shooting (2018...",68,National,0,4/24/2018 9:00,Unknown,Gun owners who favor increased restrictions ca...,The New York Times,News,https://www.nytimes.com/2018/04/24/us/gun-owne...
19,5adef226068401528a2aa51f,1945,By WALTER ISAACSON,article,The Right Stuff,"['Books and Literature', 'Musk, Elon', 'Bezos,...",66,BookReview,10,4/24/2018 9:00,Book Review,"Two new books, “The Space Barons” and “Rocket ...",The New York Times,Review,https://www.nytimes.com/2018/04/24/books/revie...
20,5adef221068401528a2aa517,684,By DAN AMIRA,article,Jimmy Carter Knows What North Korea Wants,"['United States International Relations', 'Pol...",68,Magazine,54,4/24/2018 9:00,Unknown,The 39th president of the United States on int...,The New York Times,News,https://www.nytimes.com/2018/04/24/magazine/ji...
21,5adef221068401528a2aa516,6780,By JASON ZENGERLE,article,The Truth Is Out There,['Russian Interference in 2016 US Elections an...,68,Magazine,43,4/24/2018 9:00,Unknown,In inquiries on Benghazi and Russia and beyond...,The New York Times,News,https://www.nytimes.com/2018/04/24/magazine/ho...
22,5adef218068401528a2aa514,1320,By NICK CORASANITI,article,New Jersey Ruling Could Reignite Battle Over C...,"['Religion-State Relations', 'Morristown (NJ)'...",68,Metro,0,4/24/2018 9:00,Unknown,A decision by the state’s Supreme Court barrin...,The New York Times,News,https://www.nytimes.com/2018/04/24/nyregion/ne...
23,5aded6a7068401528a2aa4e0,101,By NATALIE PROULX,article,Procrastinating,[],63,Learning,0,4/24/2018 7:03,Unknown,"Are you a procrastinator, a pre-crastinator (s...",The New York Times,News,https://www.nytimes.com/2018/04/24/learning/pr...
24,5adec85b068401528a2aa4c1,191,By THE LEARNING NETWORK,article,Word + Quiz: dilatory,[],0,Learning,0,4/24/2018 6:02,Unknown,This word has appeared in two articles on nyti...,The New York Times,News,https://www.nytimes.com/2018/04/24/learning/24...
25,5adeae5b068401528a2aa48c,1287,By MAGGIE MENDITTO,article,My Life-Threatening Bout With E. Coli Food Poi...,"['Kidneys', 'Food Contamination and Poisoning'...",68,Well,0,4/24/2018 4:11,Eat,"Before my illness, I was a healthy 22-year-old...",The New York Times,News,https://www.nytimes.com/2018/04/24/well/eat/e-...
26,5adea843068401528a2aa47a,1538,By DAVID SEGAL,article,"Choosing Brexit, a Town Yearned for Its Seafar...","['Grimsby (England)', 'International Trade and...",68,Business,1,4/24/2018 3:45,Unknown,"Branded “idiots,” residents of Grimsby, Englan...",The New York Times,News,https://www.nytimes.com/2018/04/23/business/gr...
27,5ade8fa4068401528a2aa465,912,By DEB AMLEN,article,A Quote Disproved,"['Crossword Puzzles', 'Ellis, Bret Easton', 'E...",68,Games,0,4/24/2018 2:00,Unknown,Peter Gordon takes on a metaphysical poet.,The New York Times,News,https://www.nytimes.com/2018/04/23/crosswords/...
28,5ade8c22068401528a2aa460,1209,By JESSE GREEN,article,Hot Stuff Turns Cold,"['Theater', 'Lunt-Fontanne Theater', 'Summer: ...",68,Culture,1,4/24/2018 1:45,Unknown,The late Queen of Disco and pioneer of electro...,The New York Times,Review,https://www.nytimes.com/2018/04/23/theater/rev...
29,5ade8a5b068401528a2aa45d,1053,By ANDREW ROSS SORKIN,article,"At the Top, The Pay Gap May Be Gone","['Discrimination', 'Executive Compensation', '...",68,Business,1,4/24/2018 1:37,DealBook,Women still earn far less for every dollar tha...,The New York Times,News,https://www.nytimes.com/2018/04/23/business/de...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1294,5ae76aaf068401528a2ab804,1095,By LISA DAMOUR,article,Parenting the Fortnite Addict,"['Computer and Video Games', 'Parenting', 'Chi...",68,Well,0,4/30/2018 19:12,Family,Help for parents bewildered by the sense that ...,The New York Times,News,https://www.nytimes.com/2018/04/30/well/family...
1295,5ae76cd6068401528a2ab809,1139,By ANDREW ROSS SORKIN,article,Unknown,"['Wireless Communications', 'Cellular Telephon...",68,Business,0,4/30/2018 19:21,DealBook,The two wireless carriers argue that a merger ...,The New York Times,News,https://www.nytimes.com/2018/04/30/business/de...
1296,5ae76fcc068401528a2ab818,843,By ROBERT E. RUBIN,article,Philosophy Pays Off,"['Colleges and Universities', 'Philosophy', 'C...",68,OpEd,27,4/30/2018 19:34,Unknown,Plato and existentialism helped more than cour...,The New York Times,Op-Ed,https://www.nytimes.com/2018/04/30/opinion/rob...
1297,5ae77514068401528a2ab824,1323,By PAULINA VILLEGAS,article,Disappearances Highlight the Military’s Role i...,"['Chihuahua (Mexico)', 'Missing Persons', 'Hum...",68,Foreign,12,4/30/2018 19:57,Americas,The abductions of three people by armed men in...,The New York Times,News,https://www.nytimes.com/2018/04/30/world/ameri...
1298,5ae77c97068401528a2ab835,1782,"By DAVID M. HALBFINGER, DAVID E. SANGER and RO...",article,Israel Says Secret Documents Detail Iran’s Ato...,"['Nuclear Weapons', 'Iran', 'Israel', 'United ...",68,Foreign,1,4/30/2018 20:29,Middle East,Prime Minister Benjamin Netanyahu cited no evi...,The New York Times,News,https://www.nytimes.com/2018/04/30/world/middl...
1299,5ae788d2068401528a2ab85c,1461,By MATT PHILLIPS and JIM TANKERSLEY,article,Investment Holds Steady After Tax Cut,"['Tax Cuts and Jobs Act (2017)', 'Trump, Donal...",68,Business,1,4/30/2018 21:21,Unknown,Analysts are still waiting for hard evidence t...,The New York Times,News,https://www.nytimes.com/2018/04/30/business/th...
1300,5ae791e4068401528a2ab876,113,By LOU CRAFT,article,God Save the Q,"['Poetry and Poets', 'Second Avenue (Manhattan...",0,Metro,0,4/30/2018 22:00,Unknown,"Other routes are brutish, beastly, but this on...",The New York Times,News,https://www.nytimes.com/2018/04/30/nyregion/me...
1301,5ae79a1a068401528a2ab88b,1566,By KENNETH CHANG,article,Let’s Look Inside,"['Mars InSight (Spacecraft)', 'Mars (Planet)',...",66,Science,1,4/30/2018 22:35,Unknown,The newest mission to Mars is to launch on Sat...,The New York Times,News,https://www.nytimes.com/2018/04/30/science/mar...
1302,5ae79ecd068401528a2ab893,894,By PAUL KRUGMAN,article,How’s That Tax Cut Working Out?,"['Corporate Taxes', 'United States Politics an...",68,OpEd,26,4/30/2018 22:55,Unknown,"Workers won’t see significant gains soon, if e...",The New York Times,Op-Ed,https://www.nytimes.com/2018/04/30/opinion/rep...
1303,5ae79f0c068401528a2ab894,1295,By KIRK SEMPLE,article,Border Standoff Eases As U.S. Officials Allow ...,"['Central America', 'Mexico', 'United States',...",68,Foreign,12,4/30/2018 22:56,Americas,Border officials had said they lacked capacity...,The New York Times,News,https://www.nytimes.com/2018/04/30/world/ameri...
1304,5ae7a00b068401528a2ab896,862,By DAVID BROOKS,article,The Place That Assumes Beauty,"['Italy', 'Cometa', 'Foster Care', 'Children a...",68,OpEd,27,4/30/2018 23:00,Unknown,A village-size compound called Cometa helps ch...,The New York Times,Op-Ed,https://www.nytimes.com/2018/04/30/opinion/lov...
1305,5ae7a68c068401528a2ab8a5,702,By THE EDITORIAL BOARD,article,Another Telecom Mega-Merger,"['Wireless Communications', 'Mergers, Acquisit...",68,Editorial,26,4/30/2018 23:28,Unknown,The wireless companies are trying to win over ...,The New York Times,Editorial,https://www.nytimes.com/2018/04/30/opinion/tmo...
1306,5ae7a6c6068401528a2ab8a8,1068,By SHEERA FRENKEL,article,"Facebook Tightens Privacy Policy, and App Make...","['Social Media', 'Facebook Inc', 'Data-Mining ...",68,Business,4,4/30/2018 23:29,Unknown,As Facebook prepares to hold its annual develo...,The New York Times,News,https://www.nytimes.com/2018/04/30/technology/...
1307,5ae7a739068401528a2ab8a9,850,By MICHELLE GOLDBERG,article,Truth vs. Power In the Russia Investigation,['Russian Interference in 2016 US Elections an...,68,OpEd,27,4/30/2018 23:31,Unknown,House Republicans try to cover up evidence of ...,The New York Times,Op-Ed,https://www.nytimes.com/2018/04/30/opinion/tru...
1308,5ae7ab82068401528a2ab8ae,1725,By ELIZABETH WILLIAMSON,article,‘It Couple’ Ride Trump Wave Dividing the G.O.P.,"['Schlapp, Matt (1967- )', 'Schlapp, Mercedes'...",67,Washington,1,4/30/2018 23:49,Politics,"Matt and Mercedes Schlapp, conservatives who s...",The New York Times,News,https://www.nytimes.com/2018/04/30/us/politics...
1309,5ae7ae83068401528a2ab8b3,1291,By ANA SWANSON,article,U.S. Delaying Start of Tariffs For Key Allies,"['United States Politics and Government', 'Cus...",68,Business,1,5/1/2018 0:02,Politics,"President Trump will give Canada, Mexico and t...",The New York Times,News,https://www.nytimes.com/2018/04/30/us/politics...
1310,5ae7aebe068401528a2ab8b4,1693,By ANA SWANSON and KEITH BRADSHER,article,U.S. May Limit Access for Chinese Researchers,"['China', 'Research', 'Intellectual Property',...",68,Business,1,5/1/2018 0:03,Politics,"The administration, fearing Chinese technologi...",The New York Times,News,https://www.nytimes.com/2018/04/30/us/politics...
1311,5ae7b159068401528a2ab8ba,811,By BENJAMIN WEISER and NATE SCHWEBER,article,Sheldon Silver Retrial Revisits Fraud Case,"['Bribery and Kickbacks', 'Politics and Govern...",68,Metro,20,5/1/2018 0:14,Unknown,"Mr. Silver, the once powerful Assembly speaker...",The New York Times,News,https://www.nytimes.com/2018/04/30/nyregion/sh...
1312,5ae7b224068401528a2ab8bb,667,By NOAM SCHEIBER,article,Gig Economy Dealt a Blow By a Ruling In Califo...,"['Wages and Salaries', 'Car Services and Liver...",67,Business,6,5/1/2018 0:17,Economy,The state’s highest court made it much harder ...,The New York Times,News,https://www.nytimes.com/2018/04/30/business/ec...
1313,5ae7b6a5068401528a2ab8c3,638,By ADAM BAIDAWI,article,Cardinal Faces Trial On Charges Of Sex Abuse,"['Pell, George (1941- )', 'Sex Crimes', 'Child...",68,Foreign,12,5/1/2018 0:36,Australia,An Australian court has ruled that the cardina...,The New York Times,News,https://www.nytimes.com/2018/04/30/world/austr...
1314,5ae7b8d5068401528a2ab8c6,3074,By MATT APUZZO and MICHAEL S. SCHMIDT,article,"The Questions, With Context",['Russian Interference in 2016 US Elections an...,68,Washington,16,5/1/2018 0:46,Politics,The questions show the special counsel’s focus...,The New York Times,News,https://www.nytimes.com/2018/04/30/us/politics...
1315,5ae7b8e9068401528a2ab8c7,1452,By MICHAEL S. SCHMIDT,article,Questions for President Show Depth of Inquiry ...,['Russian Interference in 2016 US Elections an...,68,Washington,1,5/1/2018 0:46,Politics,The questions provide the most detailed look y...,The New York Times,News,https://www.nytimes.com/2018/04/30/us/politics...
1316,5ae7ca23068401528a2ab8e3,562,By DEB AMLEN,article,Watch Out for the Obstacles,"['Crossword Puzzles', 'Stulberg, Jacob (Crossw...",68,Games,0,5/1/2018 2:00,Unknown,Jacob Stulberg points out the speed bumps in h...,The New York Times,News,https://www.nytimes.com/2018/04/30/crosswords/...
1317,5ae82b68068401528a2ab966,1766,By JENNIFER A. KINGSON,article,A Competitive Team Sport. For Your Dog.,"['Dogs', 'Athletics and Sports', 'Exercise', '...",68,Well,0,5/1/2018 8:55,Unknown,"Flyball, in which four-dog teams compete in a ...",The New York Times,News,https://www.nytimes.com/2018/05/01/well/dog-fl...
1318,5ae82c97068401528a2ab96c,785,By NICOLE LAMY,article,Dear Match Book: Fiction that Takes Us Back to...,['Books and Literature'],66,BookReview,0,5/1/2018 9:00,Book Review,"From the bones of 15th-century monarchs, to Ne...",The New York Times,News,https://www.nytimes.com/2018/05/01/books/revie...
1319,5ae82c93068401528a2ab969,1004,By CLAIRE CAIN MILLER,article,This Common Question Reinforces the Gender Pay...,"['Discrimination', 'Wages and Salaries', 'Labo...",68,Upshot,3,5/1/2018 9:00,Unknown,Several states and cities have ordered employe...,The New York Times,News,https://www.nytimes.com/2018/05/01/upshot/how-...
1320,5ae82c95068401528a2ab96b,1043,By TRACY J. GATES,article,"Anna, Llama and Me","['Friendship', 'Dewdney, Anna', 'Writing and W...",65,Well,0,5/1/2018 9:00,Family,"The beginning, middle and end of a picture boo...",The New York Times,News,https://www.nytimes.com/2018/05/01/well/family...
1321,5ae82c9d068401528a2ab96d,659,Interview by AUDIE CORNISH,article,Gen. Michael Hayden Has One Regret: Russia,"['Classified Information and State Secrets', '...",66,Magazine,70,5/1/2018 9:00,Unknown,"The former N.S.A. and C.I.A. chief on Trump, S...",The New York Times,News,https://www.nytimes.com/2018/05/01/magazine/ge...
1322,5ae82c9f068401528a2ab96f,1155,By JASON ROBERT BROWN,article,There Is Nothin’ Like a Tune,"['Books and Literature', 'Purdum, Todd S', 'Th...",68,BookReview,17,5/1/2018 9:00,Book Review,"In “Something Wonderful,” Todd S. Purdum analy...",The New York Times,Review,https://www.nytimes.com/2018/05/01/books/revie...
1323,5ae82ca3068401528a2ab97a,2055,By MICHAEL PAULSON,article,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",68,Culture,0,5/1/2018 9:00,Unknown,"A pair of two-part productions, “Harry Potter ...",The New York Times,News,https://www.nytimes.com/2018/05/01/theater/ton...

In [5]:
# Delete extraneous column
df_Articles_Apr.columns

Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')

In [6]:
# Delete extraneous column
df_Articles_Apr_clean = df_Articles_Apr[['articleID', 'headline',
       'keywords',  'newDesk',  'pubDate',
       'sectionName', 'snippet', 'typeOfMaterial', 'webURL']]
df_Articles_Feb_clean = df_Articles_Feb[['articleID', 'headline',
       'keywords',  'newDesk', 'pubDate',
       'sectionName', 'snippet', 'typeOfMaterial', 'webURL']]
df_Articles_Jan_clean = df_Articles_Jan[['articleID', 'headline',
       'keywords',  'newDesk',  'pubDate',
       'sectionName', 'snippet', 'typeOfMaterial', 'webURL']]
df_Articles_Mar_clean = df_Articles_Mar[['articleID', 'headline',
       'keywords',  'newDesk', 'pubDate',
       'sectionName', 'snippet', 'typeOfMaterial', 'webURL']]

In [7]:
# Appending the dataframes togehter
df_Articles_Clean = df_Articles_Jan_clean.append(df_Articles_Feb_clean, ignore_index=True)
df_Articles_Clean = df_Articles_Clean.append(df_Articles_Mar_clean, ignore_index=True)
df_Articles_Clean = df_Articles_Clean.append(df_Articles_Apr_clean, ignore_index=True)

In [8]:
# Verify dropped rows
df_Articles_Clean.columns = ['Article_ID', 'Headline', 'Keywords', 'News_Category', 'Pub_Date',
       'Section_Name', 'Snippet', 'Media_Type', 'URL']
df_Articles_Clean.count()

Article_ID       4769
Headline         4769
Keywords         4769
News_Category    4769
Pub_Date         4769
Section_Name     4769
Snippet          4769
Media_Type       4769
URL              4769
dtype: int64

In [9]:
df_Articles_Clean = df_Articles_Clean[df_Articles_Clean.News_Category != 'Video']
df_Articles_Clean = df_Articles_Clean[df_Articles_Clean.News_Category != 'Unknown']
df_Articles_Clean.count()

Article_ID       4755
Headline         4755
Keywords         4755
News_Category    4755
Pub_Date         4755
Section_Name     4755
Snippet          4755
Media_Type       4755
URL              4755
dtype: int64

In [10]:
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
Arts&Leisure,62,62,62,62,62,62,62,62
BookReview,50,50,50,50,50,50,50,50
Business,293,293,293,293,293,293,293,293
Climate,31,31,31,31,31,31,31,31
Culture,269,269,269,269,269,269,269,269
Dining,159,159,159,159,159,159,159,159
Editorial,104,104,104,104,104,104,104,104
Express,19,19,19,19,19,19,19,19
Foreign,289,289,289,289,289,289,289,289
Games,160,160,160,160,160,160,160,160
Insider,47,47,47,47,47,47,47,47
Investigative,26,26,26,26,26,26,26,26
Learning,245,245,245,245,245,245,245,245
Letters,3,3,3,3,3,3,3,3
Magazine,124,124,124,124,124,124,124,124
Metro,313,313,313,313,313,313,313,313
Metropolitan,31,31,31,31,31,31,31,31
NYTNow,4,4,4,4,4,4,4,4
National,272,272,272,272,272,272,272,272
NewsDesk,31,31,31,31,31,31,31,31
Obits,22,22,22,22,22,22,22,22
OpEd,777,777,777,777,777,777,777,777
Photo,39,39,39,39,39,39,39,39
Podcasts,38,38,38,38,38,38,38,38
Politics,20,20,20,20,20,20,20,20
RealEstate,180,180,180,180,180,180,180,180
Science,119,119,119,119,119,119,119,119
Smarter Living,31,31,31,31,31,31,31,31
Society,2,2,2,2,2,2,2,2
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Styles,47,47,47,47,47,47,47,47
Summary,2,2,2,2,2,2,2,2
SundayBusiness,30,30,30,30,30,30,30,30
TStyle,14,14,14,14,14,14,14,14
Travel,57,57,57,57,57,57,57,57
Upshot,82,82,82,82,82,82,82,82
Washington,378,378,378,378,378,378,378,378
Weekend,58,58,58,58,58,58,58,58
Well,199,199,199,199,199,199,199,199

In [11]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Arts&Leisure': 'Entertainment', 'BookReview': 'Entertainment', 'Dining': 'Entertainment'})

In [12]:
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
Business,293,293,293,293,293,293,293,293
Climate,31,31,31,31,31,31,31,31
Culture,269,269,269,269,269,269,269,269
Editorial,104,104,104,104,104,104,104,104
Entertainment,271,271,271,271,271,271,271,271
Express,19,19,19,19,19,19,19,19
Foreign,289,289,289,289,289,289,289,289
Games,160,160,160,160,160,160,160,160
Insider,47,47,47,47,47,47,47,47
Investigative,26,26,26,26,26,26,26,26
Learning,245,245,245,245,245,245,245,245
Letters,3,3,3,3,3,3,3,3
Magazine,124,124,124,124,124,124,124,124
Metro,313,313,313,313,313,313,313,313
Metropolitan,31,31,31,31,31,31,31,31
NYTNow,4,4,4,4,4,4,4,4
National,272,272,272,272,272,272,272,272
NewsDesk,31,31,31,31,31,31,31,31
Obits,22,22,22,22,22,22,22,22
OpEd,777,777,777,777,777,777,777,777
Photo,39,39,39,39,39,39,39,39
Podcasts,38,38,38,38,38,38,38,38
Politics,20,20,20,20,20,20,20,20
RealEstate,180,180,180,180,180,180,180,180
Science,119,119,119,119,119,119,119,119
Smarter Living,31,31,31,31,31,31,31,31
Society,2,2,2,2,2,2,2,2
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Styles,47,47,47,47,47,47,47,47
Summary,2,2,2,2,2,2,2,2
SundayBusiness,30,30,30,30,30,30,30,30
TStyle,14,14,14,14,14,14,14,14
Travel,57,57,57,57,57,57,57,57
Upshot,82,82,82,82,82,82,82,82
Washington,378,378,378,378,378,378,378,378
Weekend,58,58,58,58,58,58,58,58
Well,199,199,199,199,199,199,199,199

In [13]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Business': " News & Politics",
    "Express" : " News & Politics",
    "Investigative" : " News & Politics",
    "Metro" : " News & Politics",
    "Metropolitan" : " News & Politics",
    "NYTNow" : " News & Politics",
    "National" : " News & Politics",
    "Politics" : " News & Politics",
    "SundayBusiness" : " News & Politics",
    "Washington" : " News & Politics",
    "Weekend" : " News & Politics",
    "NewsDesk" : " News & Politics",
    "Insider" : " News & Politics",
   "SundayNews & Politics":  " News & Politics"})

In [14]:
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
Climate,31,31,31,31,31,31,31,31
Culture,269,269,269,269,269,269,269,269
Editorial,104,104,104,104,104,104,104,104
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
Games,160,160,160,160,160,160,160,160
Learning,245,245,245,245,245,245,245,245
Letters,3,3,3,3,3,3,3,3
Magazine,124,124,124,124,124,124,124,124
Obits,22,22,22,22,22,22,22,22
OpEd,777,777,777,777,777,777,777,777
Photo,39,39,39,39,39,39,39,39
Podcasts,38,38,38,38,38,38,38,38
RealEstate,180,180,180,180,180,180,180,180
Science,119,119,119,119,119,119,119,119
Smarter Living,31,31,31,31,31,31,31,31
Society,2,2,2,2,2,2,2,2
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Styles,47,47,47,47,47,47,47,47
Summary,2,2,2,2,2,2,2,2
TStyle,14,14,14,14,14,14,14,14
Travel,57,57,57,57,57,57,57,57
Upshot,82,82,82,82,82,82,82,82
Well,199,199,199,199,199,199,199,199

In [15]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Culture': " Travel & Events",
    'Travel': " Travel & Events"
})
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
Travel & Events,326,326,326,326,326,326,326,326
Climate,31,31,31,31,31,31,31,31
Editorial,104,104,104,104,104,104,104,104
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
Games,160,160,160,160,160,160,160,160
Learning,245,245,245,245,245,245,245,245
Letters,3,3,3,3,3,3,3,3
Magazine,124,124,124,124,124,124,124,124
Obits,22,22,22,22,22,22,22,22
OpEd,777,777,777,777,777,777,777,777
Photo,39,39,39,39,39,39,39,39
Podcasts,38,38,38,38,38,38,38,38
RealEstate,180,180,180,180,180,180,180,180
Science,119,119,119,119,119,119,119,119
Smarter Living,31,31,31,31,31,31,31,31
Society,2,2,2,2,2,2,2,2
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Styles,47,47,47,47,47,47,47,47
Summary,2,2,2,2,2,2,2,2
TStyle,14,14,14,14,14,14,14,14
Upshot,82,82,82,82,82,82,82,82
Well,199,199,199,199,199,199,199,199

In [16]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Climate': " Science & Technology",
    'Science': " Science & Technology",
    "Upshot": " Science & Technology"
})
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
Science & Technology,232,232,232,232,232,232,232,232
Travel & Events,326,326,326,326,326,326,326,326
Editorial,104,104,104,104,104,104,104,104
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
Games,160,160,160,160,160,160,160,160
Learning,245,245,245,245,245,245,245,245
Letters,3,3,3,3,3,3,3,3
Magazine,124,124,124,124,124,124,124,124
Obits,22,22,22,22,22,22,22,22
OpEd,777,777,777,777,777,777,777,777
Photo,39,39,39,39,39,39,39,39
Podcasts,38,38,38,38,38,38,38,38
RealEstate,180,180,180,180,180,180,180,180
Smarter Living,31,31,31,31,31,31,31,31
Society,2,2,2,2,2,2,2,2
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Styles,47,47,47,47,47,47,47,47
Summary,2,2,2,2,2,2,2,2
TStyle,14,14,14,14,14,14,14,14
Well,199,199,199,199,199,199,199,199

In [17]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Editorial': " People & Blogs",
    'Letters': " People & Blogs",
    'Magazine': " People & Blogs",
    'Obits': " People & Blogs",
    'OpEd': " People & Blogs",
    'Society': " People & Blogs",
    'Podcasts': " People & Blogs"
    
})
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
People & Blogs,1070,1070,1070,1070,1070,1070,1070,1070
Science & Technology,232,232,232,232,232,232,232,232
Travel & Events,326,326,326,326,326,326,326,326
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
Games,160,160,160,160,160,160,160,160
Learning,245,245,245,245,245,245,245,245
Photo,39,39,39,39,39,39,39,39
RealEstate,180,180,180,180,180,180,180,180
Smarter Living,31,31,31,31,31,31,31,31
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Styles,47,47,47,47,47,47,47,47
Summary,2,2,2,2,2,2,2,2
TStyle,14,14,14,14,14,14,14,14
Well,199,199,199,199,199,199,199,199

In [18]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Games': " Gaming"
    
})
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
Gaming,160,160,160,160,160,160,160,160
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
People & Blogs,1070,1070,1070,1070,1070,1070,1070,1070
Science & Technology,232,232,232,232,232,232,232,232
Travel & Events,326,326,326,326,326,326,326,326
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
Learning,245,245,245,245,245,245,245,245
Photo,39,39,39,39,39,39,39,39
RealEstate,180,180,180,180,180,180,180,180
Smarter Living,31,31,31,31,31,31,31,31
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Styles,47,47,47,47,47,47,47,47
Summary,2,2,2,2,2,2,2,2
TStyle,14,14,14,14,14,14,14,14
Well,199,199,199,199,199,199,199,199

In [19]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Learning': " Education",
    'Photo': " Education",
    'RealEstate': " Education"
    
})
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
Education,464,464,464,464,464,464,464,464
Gaming,160,160,160,160,160,160,160,160
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
People & Blogs,1070,1070,1070,1070,1070,1070,1070,1070
Science & Technology,232,232,232,232,232,232,232,232
Travel & Events,326,326,326,326,326,326,326,326
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
Smarter Living,31,31,31,31,31,31,31,31
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Styles,47,47,47,47,47,47,47,47
Summary,2,2,2,2,2,2,2,2
TStyle,14,14,14,14,14,14,14,14
Well,199,199,199,199,199,199,199,199

In [20]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Smarter Living': " Howto & Style",
    'Styles': " Howto & Style",
    'TStyle': " Howto & Style",
    'Well': " Howto & Style"
    
})
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
Education,464,464,464,464,464,464,464,464
Gaming,160,160,160,160,160,160,160,160
Howto & Style,291,291,291,291,291,291,291,291
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
People & Blogs,1070,1070,1070,1070,1070,1070,1070,1070
Science & Technology,232,232,232,232,232,232,232,232
Travel & Events,326,326,326,326,326,326,326,326
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
SpecialSections,13,13,13,13,13,13,13,13
Sports,115,115,115,115,115,115,115,115
Summary,2,2,2,2,2,2,2,2

In [21]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'SpecialSections': " Autos & Vehicles"
    
})
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
Autos & Vehicles,13,13,13,13,13,13,13,13
Education,464,464,464,464,464,464,464,464
Gaming,160,160,160,160,160,160,160,160
Howto & Style,291,291,291,291,291,291,291,291
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
People & Blogs,1070,1070,1070,1070,1070,1070,1070,1070
Science & Technology,232,232,232,232,232,232,232,232
Travel & Events,326,326,326,326,326,326,326,326
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
Sports,115,115,115,115,115,115,115,115
Summary,2,2,2,2,2,2,2,2

In [22]:
df_Articles_Clean['News_Category'] = df_Articles_Clean['News_Category'].replace(
   {'Summary': " Documentary"
    
})
df_Articles_Clean.groupby(['News_Category']).count()

,Article_ID,Headline,Keywords,Pub_Date,Section_Name,Snippet,Media_Type,URL
News_Category,,,,,,,,
Autos & Vehicles,13,13,13,13,13,13,13,13
Documentary,2,2,2,2,2,2,2,2
Education,464,464,464,464,464,464,464,464
Gaming,160,160,160,160,160,160,160,160
Howto & Style,291,291,291,291,291,291,291,291
News & Politics,1522,1522,1522,1522,1522,1522,1522,1522
People & Blogs,1070,1070,1070,1070,1070,1070,1070,1070
Science & Technology,232,232,232,232,232,232,232,232
Travel & Events,326,326,326,326,326,326,326,326
Entertainment,271,271,271,271,271,271,271,271
Foreign,289,289,289,289,289,289,289,289
Sports,115,115,115,115,115,115,115,115

In [23]:
df_Articles_Clean.to_csv(r'C:\Users\conta\Social_Media_Bonanza\Resources\Articles_Clean_v2.csv', index=False)