<h3><center>Merge and Clean YouTube Data</center></h3>

In [1]:
import pandas as pd 
import numpy as np 
import datetime as dt

In [2]:
# Load YouTube data and YouTube Category ID data
youtube_csv = ('Resources/USvideos.csv')
cat_id_csv = ('Resources/YTCategory.csv')

In [3]:
# Convert YouTube Data into DataFrame 
youtube_df = pd.read_csv(youtube_csv)
youtube_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [4]:
# Convert Category ID data into DataFrame 
cat_id_df = pd.read_csv(cat_id_csv)
cat_id_df.head()

   category_id           Cat_Name
0            2   Autos & Vehicles
1            1   Film & Animation
2           10              Music
3           15     Pets & Animals
4           17             Sports

In [5]:
# Merge YouTube DF and Category DF
youtube_data = pd.merge(youtube_df, cat_id_df, on='category_id')
youtube_data.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Cat_Name
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,People & Blogs
1,0mlNzVSJrT0,17.14.11,Me-O Cats Commercial,Nobrand,22,2017-04-21T06:47:32.000Z,"cute|""cats""|""thai""|""eggs""",98966,2486,184,532,https://i.ytimg.com/vi/0mlNzVSJrT0/default.jpg,False,False,False,Kittens come out of the eggs in a Thai commerc...,People & Blogs
2,STI2fI7sKMo,17.14.11,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",Shawn Johnson East,22,2017-11-11T15:00:03.000Z,"shawn johnson|""andrew east""|""shawn east""|""shaw...",321053,4451,1772,895,https://i.ytimg.com/vi/STI2fI7sKMo/default.jpg,False,False,False,Subscribe for weekly videos ▶ http://bit.ly/sj...,People & Blogs
3,KODzih-pYlU,17.14.11,BLIND(folded) CAKE DECORATING CONTEST (with Mo...,Grace Helbig,22,2017-11-11T18:08:04.000Z,"itsgrace|""funny""|""comedy""|""vlog""|""grace""|""helb...",197062,7250,217,456,https://i.ytimg.com/vi/KODzih-pYlU/default.jpg,False,False,False,Molly is an god damn amazing human and she cha...,People & Blogs
4,8mhTWqWlQzU,17.14.11,Wearing Online Dollar Store Makeup For A Week,Safiya Nygaard,22,2017-11-11T01:19:33.000Z,wearing online dollar store makeup for a week|...,2744430,115426,1110,6541,https://i.ytimg.com/vi/8mhTWqWlQzU/default.jpg,False,False,False,I found this online dollar store called ShopMi...,People & Blogs

In [6]:
# create a new column, date_parsed, with the parsed dates
youtube_data['trending_date'] = pd.to_datetime(youtube_data['trending_date'], format = "%y.%d.%m")

In [7]:
# Convert Pub_Date column into date format and remove time
youtube_data['trending_date'] = pd.to_datetime(youtube_data['trending_date']).dt.date
youtube_data.tail()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Cat_Name
40944,V6ElE2xs48c,2018-06-02,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1324482,22413,608,1644,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",Shows
40945,V6ElE2xs48c,2018-06-03,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1332252,22461,610,1648,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",Shows
40946,V6ElE2xs48c,2018-06-04,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1340039,22504,615,1648,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",Shows
40947,V6ElE2xs48c,2018-06-05,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1345086,22542,615,1649,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",Shows
40948,V6ElE2xs48c,2018-06-06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1351321,22587,616,1649,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",Shows

In [8]:
# Clean Merged DF
youtube_data_clean = youtube_data[['category_id', 'Cat_Name', 'trending_date', 'title', 'channel_title',  'tags', 'views', 'likes', 'comment_count']]
youtube_data_clean.head()

,category_id,Cat_Name,trending_date,title,channel_title,tags,views,likes,comment_count
0,22,People & Blogs,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,SHANtell martin,748374,57527,15954
1,22,People & Blogs,2017-11-14,Me-O Cats Commercial,Nobrand,"cute|""cats""|""thai""|""eggs""",98966,2486,532
2,22,People & Blogs,2017-11-14,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",Shawn Johnson East,"shawn johnson|""andrew east""|""shawn east""|""shaw...",321053,4451,895
3,22,People & Blogs,2017-11-14,BLIND(folded) CAKE DECORATING CONTEST (with Mo...,Grace Helbig,"itsgrace|""funny""|""comedy""|""vlog""|""grace""|""helb...",197062,7250,456
4,22,People & Blogs,2017-11-14,Wearing Online Dollar Store Makeup For A Week,Safiya Nygaard,wearing online dollar store makeup for a week|...,2744430,115426,6541

In [9]:
# Update Columns 
youtube_data_clean.columns = ['Category_ID', 'Category', 'Date', 'Video_Title', 'Channel',
       'Tags', 'Total_Views', 'Total_Likes', 'Comments_Count']

In [10]:
youtube_data_clean.tail()

,Category_ID,Category,Date,Video_Title,Channel,Tags,Total_Views,Total_Likes,Comments_Count
40944,43,Shows,2018-06-02,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1324482,22413,1644
40945,43,Shows,2018-06-03,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1332252,22461,1648
40946,43,Shows,2018-06-04,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1340039,22504,1648
40947,43,Shows,2018-06-05,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1345086,22542,1649
40948,43,Shows,2018-06-06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1351321,22587,1649

In [11]:
youtube_data_clean.to_csv(r'C:\Users\conta\Social_Media_Bonanza\Resources\YouTube_Clean.csv', index=False)